server:
    port: 8081

example:
    client:
        address:
            url: http://localhost:8082/addresses

spring:
    data:
        mongodb:
            uri: mongodb://localhost:27017/cleanarch
