version: "3.1"

services:
    zookeeper:
        restart: on-failure
        image: confluentinc/cp-zookeeper:latest
        environment:
            ZOOKEEPER_CLIENT_PORT: 2181
            ZOOKEEPER_TICK_TIME: 2000
        networks:
            - cleanarch

    kafka:
        restart: on-failure
        image: confluentinc/cp-kafka:latest
        depends_on:
            - zookeeper
        ports:
            - "9092:9092"
        environment:
            KAFKA_BROKER_ID: 1
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
            KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
        networks:
            - cleanarch

    mongo:
        restart: on-failure
        image: mongo:5.0
        ports:
            - "27017:27017"
        networks:
            - cleanarch

    kafka-ui:
        restart: on-failure
        image: provectuslabs/kafka-ui:latest
        ports:
            - "8097:8080"
        depends_on:
            - zookeeper
            - kafka
        environment:
            KAFKA_CLUSTERS_0_NAME: local
            KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: docker-local-kafka-1:29092
            KAFKA_CLUSTERS_0_ZOOKEEPER: docker-local-zookeeper-1:2181
        networks:
            - cleanarch

networks:
    cleanarch:
        driver: bridge
